services:
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=8000"

  client:
    container_name: client
    build: 
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - server


  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data: