{
 "title": "Client - Server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"python-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests per 1 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(request_count_total{job=\"python-server\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps de requête",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"python-server\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}