global:
  scrape_interval: 2s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'python-server'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    static_configs:
    - targets: ['server:8000']